### ISSUE TITLE
Can't use IPv6 resolvers

### ISSUE THREAD

**Issue by Natolumin** [MickaelBergem/dnsstresss#3]
It doesn't seem possible, with the current cli, to use ipv6 addresses, because of the `ip:port` format of the `-r` argument.

This form obviously doesn't work : 

```
    ./dnsstresss -r 2001:4860:4860::8888:53 google.com.
```

This one (often used with ipv6 literals that need port information) doesn't seem to work either : 

```
    ./dnsstresss -r [2001:4860:4860::8888]:53 google.com.
```

**Comment by bortzmeyer** [comment]
Using just the IPv6 address gives no error message but tcpdump shows that no packet is sent.

```
% ./dnsstresss -r 2001:4b98:dc2:45:216:3eff:fe4b:8c5b .
dnsstresss - dns stress tool
Queried domains: [.].
Started 50 threads.
Started timer channel.
Requests sent: 1114734r/s   (1116250 total) Replies received: 0r/s   Errors: 1116250 (100%)
Requests sent: 1111753r/s   (2228495 total) Replies received: 0r/s   Errors: 1112245 (100%)
̀̀``
```

**Comment by MickaelBergem** [comment]
@Natolumin we need a better handling of errors at this line : https://github.com/MickaelBergem/dnsstresss/blob/master/dnsstresss.go#L128. Maybe we need to send a first "probe" request to check for errors in the DNS resolution before starting the threads.

**Comment by MickaelBergem** [comment]
@Natolumin this works for me with the latest compiled version (I only added a "pre-check" step printing the error, if any). I had to add quotes, because zsh wanted to interpret the brackets.

Can you try again?

Also @bortzmeyer, with quotes and brackets, it works for me. As of today, a more verbose error will warn you if the format is incorrect.

Hope this helps!

**Comment by MickaelBergem** [comment]
@bortzmeyer I know this is a very old thread, but the exact syntax you used is now supported, without requiring you to add brackets around the IPv6 address:

```bash
# Didn't work previously
dnsstresss -r 2001:4b98:dc2:45:216:3eff:fe4b:8c5b .
# Adding brackets is still required for non-standard ports (quotes might be required depending on your shell)
dnsstresss -r "[2001:4b98:dc2:45:216:3eff:fe4b:8c5b]:53" .
```
