### ISSUE TITLE
Go get is deprecated

### ISSUE THREAD

**Issue by Natgho** [MickaelBergem/dnsstresss#7]
Please update Readme.md, "go get" is deprecated.

**Comment by MickaelBergem** [comment]
@Natgho sorry for the delay, and thanks for spotting this. This project isn't actively maintained anymore. Do you want to submit a PR? 🥺

**Comment by Natgho** [comment]
No worries, I fixed :) 
https://github.com/MickaelBergem/dnsstresss/pull/8

**Comment by MickaelBergem** [comment]
Thanks a lot, fix merged! 🙏
